stages:
  clean:
    cmd: python scripts/clean.py
    deps:
    - data/raw/events.csv
    outs:
    - data/clean/events.csv
  transform:
    cmd: python scripts/transform.py
    deps:
    - data/clean/events.csv
    outs:
    - data/transformed/events.csv
  features:
    cmd: python scripts/features.py
    deps:
    - data/transformed/events.csv
    outs:
    - data/features/events.csv
